### PR TITLE
[WIP] Add fractions support when parsing value

### PR DESCRIPTION
**Pull request by 2426021684**
It seems to work. Not quite sure how mixed fractions work but they do. The code to parse numbers is kind of hard to understand. Maybe use [pegjs](http://pegjs.org/online)? Still have to write tests.

### CODE REVIEW

**Comment by spencermountain** [comment]
hey cool, sounds good. Make sure to write a handful of tests, this stuff is sneaky.
also, heads-up for `denom===0`.
:+1:

**Comment by 2426021684** [comment]
travis seems to be broken

**Comment by spencermountain** [comment]
yeah, i'm just working that out now. you can just ignore.
for the pegjs thing, I'm not strong about nlp_comp being the place to evaluate mathematical expressions. that would be a cool plugin. Fraction support though is cool-beans

**Comment by 2426021684** [comment]
pegjs is a general parser. Math is just an example. It can even parse javascript

**Comment by silentrob** [comment]
PegJS works great when you have a strict grammar, but natural language is a whole other beast entirely.

**Comment by spencermountain** [comment]
`'seven eleven'` and things just return null.
are you gonna support the `"1/2 million" === 500000` idea?

**Comment by 2426021684** [comment]
I am just adding simple fractions like 5 1/2 and 1/3.

**Comment by 2426021684** [comment]
@spencermountain 1/2 million works. I don't know why but it does.

**Comment by 2426021684** [comment]
@spencermountain should I add support for negative numbers too?

**Comment by spencermountain** [comment]
you are a marvelous person.

**Comment by 2426021684** [comment]
Have to get it to work when there is a space before or after the slash

**Comment by spencermountain** [comment]
that's a clever point

**Comment by 2426021684** [comment]
There are (at least) four different ways to write one-half: 1/2 ½ ¹/₂ ¹⁄₂

**Pull request merged**
