### PR TITLE
Add term.forms()

### PR DESCRIPTION
**Pull request by ilyankou**
#180

### CODE REVIEW

**Comment by spencermountain** [comment]
hey, wanna put this on the other classes too? LIke, `term.forms()` does: 
```javascript
{text:this.text, normal:this.normal}
```
and then `value.forms()` maybe returns something like,
```javascript
{text:this.text, normal:this.normal, ordinal:this.to_ordinal() ....}
```
etc? I dunno, up to you if you like it.

**Comment by spencermountain** [comment]
i tried overloading `.root()` for the first time, and it's kinda cool. That way people don't need to type-check each term before firing their method. Try it out, if you want. I'm happy to just merge this, if you're not hot on the idea

**Comment by ilyankou** [comment]
I don't quite follow: you can apply .forms() for any term, and depending on the tag it will either conjugate (verbs, adjectives) or return singular/plural for nouns – no type-checking from users. I thought of it exclusively within issue #180. But you would like this operator to basically return everything there is for a term/value?

**Comment by spencermountain** [comment]
yeah, i was thinking we could have .forms() as a method for every class of Term, like: 
* `Noun.forms()` - returns singular/plural forms
* `Verb.forms()` - conjugate, etc
* `Person.forms()` - pronoun, firstname, lastname
to sorta universalize it, in the api - like 'blow-out all derivations' or whatever. That'd be more lucid than fishing around for a `.to_bigLinguisticTerm()` method, you know? Like, `t.show_me_everything()`

**Comment by spencermountain** [comment]
or how about `term.all_forms()` ?

**Comment by ilyankou** [comment]
I created one overloaded method in Term which is inherited by all classes like Noun, Verb, etc (who inherit Term) – I thought it would be easier to manage. Noun.forms() and Verb.forms() hence works exactly as you described above - the "if" statement makes sure the right method (conjugate(), pluralize(), etc.) is called.

**Comment by ilyankou** [comment]
The thing is, for Verb and Adjective forms() basically duplicates conjugate(). But I can definitely implement this method separately in every class with appropriate fields we want to display – although again, my intention was to fix an issue, not to create something new.

**Comment by spencermountain** [comment]
ah, yeah i see. I can merge this now if you want. 
I may rename it and kick it a bit further, to `Person`, `Date` ... and maybe `Sentence`??
unless you wanted to give it a go

**Comment by ilyankou** [comment]
Go ahead and make appropriate changes – and merge when you feel it's ready!

**Pull request merged**
