### PR TITLE
Updated documentation and GitIgnore props

### PR DESCRIPTION
**Pull request by davidbuhler**
Updated documentation

### CODE REVIEW

**Comment by spencermountain** [comment]
hey david, thanks for your help.
I like having more explicit contribution instructions, did you write this, or is it a template?
Same for code-of-conduct, etc, though some of it does seem a little rigid, i could get behind it.
wanna put this stuff in the wiki instead?
cheers

**Comment by davidbuhler** [comment]
It's a mix. I pulled .MDs from major open-source projects and then I tweaked them for NLP-C.

I substituted pointers from other projects' docs for pointers to the WIKI.

**Comment by davidbuhler** [comment]
Note: I had an overarching goal; I tried to aim for a separation of concerns to improve the ease in project set-up as well as information for contributing. I'm not a text-learner, but half the developers probably are text-learners, and the documentation (while it's more of a starting point) tries to give thorough guidance on setting up the project, contributing, as well as to provide a short but succinct overview of the project.

The goal was to seed the documentation to improve project visibility, setup, and contributions.

The README.MD is in conflict, though.

**Comment by spencermountain** [comment]
what happened?
can i put that stuff in the wiki?

**Comment by davidbuhler** [comment]
Oops! I didn't think it was going to get merged in, so I closed the PR. I reopened it! Sorry about that (I'm going through ToDo items yesterday and today).

**Comment by spencermountain** [comment]
hey david, we can close this now, i've added these docs to the wiki

* readme -> [home](https://github.com/nlp-compromise/nlp_compromise/wiki)
* contributors +  code of conduct
* gitignore
i removed the bit about commit message rules, cuz that seemed burdensome, but otherwise all good.
thanks!

**Comment by davidbuhler** [comment]
👍

**Comment by davidbuhler** [comment]
Not sure if the updated CONTRIBUTING.MD has value:

https://github.com/davidbuhler/nlp_compromise/blob/dd686ea4d2f11fb762bd395b7c49f3b0b04ca444/CONTRIBUTING.md

**Comment by spencermountain** [comment]
feel free to just edit the wiki david. lots of work to do in there, go nuts!

**Pull request closed without merging**
