### PR TITLE
Add typescript typings

### PR DESCRIPTION
**Pull request by 2426021684**
Add typescript typings. You can move the d.ts file if you want.

### CODE REVIEW

**Comment by spencermountain** [comment]
cool! can i just merge it?

**Comment by 2426021684** [comment]
No yet still working

**Comment by 2426021684** [comment]
I think it is ready to be merged. Can you check it?

**Comment by spencermountain** [comment]
this is a thing of beauty. I'm really grateful to you and @eshansingh.

#162

**Comment by 2426021684** [comment]
Should I type the plugins too? They would have a separate d.ts file.

**Comment by spencermountain** [comment]
yeah, good idea - [nlp-syllables](https://github.com/nlp-compromise/nlp-syllables),  [nlp-ngram](https://github.com/nlp-compromise/nlp-ngram), and  [nlp-locale](https://github.com/nlp-compromise/nlp-locale) would love some attention - also, can you teach me/commit some kind of typescript test using the typings? I'm happy to roll our tests over, but got confused setting it up.
how does type-node find the typings?
.. like this?
```javascript
/// <reference path="../typings.d.ts" />
```

**Comment by 2426021684** [comment]
I'm not entirely sure either. After you switch to tape, I will try to convert the tests to typescript.
I think you have to use `import nlp = require("nlp_compromise")` instead of `/// <reference path="../typings.d.ts" />`.

**Comment by eshansingh** [comment]
Hey, everybody! Surprised to see this. Thanks so much @2426021684 for your help. I had a hell of a lot of other work to do, so I severely apologise for not helping as much! @spencermountain, all thanks should go to @2426021684.

**Comment by CWSpear** [comment]
Do you not support TypeScript types anymore?

**Comment by spencermountain** [comment]
hi Cameron, yeah the typings got lost in a (complete) refactor this winter. Would love some help bringing them back. The api's been cleaned-up a great deal.

I tried using closure-compiler a few weeks ago, to reduce filesize of the builds. It ingests jsdoc typings, so if that could be part of a typing solution, double-win

**Pull request merged**
