### PR TITLE
document the case of names that do not signal gender

### PR DESCRIPTION
**Pull request by vielmetti**
As noted in #117 the software attempts to guess the gender of names. The internal and external documentation should show that three gender values are defined: 'Male', 'Female', and null.

### CODE REVIEW

**Comment by seandougall** [comment]
And in the interest of accuracy, `return null;` should be moved to the first line of the function body, because no name in existence denotes gender unambiguously.

**Comment by RRorg** [comment]
You chose a bad example for `null`, since `Jan` is a valid first name (a form of Johannes in many European countries), and the return value is simply highlighting a shortcoming of the library. I recommend using a completely made-up "name".

**Comment by vielmetti** [comment]
Jan is an American female name, short form for Janet. The example illustrates that the library does not distinguish currently between unknown names of unknown gender vs. known names of indeterminate gender.

-----Original Message-----

**Comment by spencermountain** [comment]
thanks edward, will merge this later in the week, when things quiet down. ;)
thanks for your help.

**Comment by alexbrault** [comment]
@RRorg: returning null doesn't mean "this is not a valid name", it means "I can't tell whether it refers to a male or female individual".

**Comment by RRorg** [comment]
Maybe working with confidence scores instead would be a better solution.

**Pull request merged**
