### PR TITLE
Resolve #145

### LINKED ISSUE #145: Incorrect Negation for Statements Such as "I enjoy...."
Statements such as "I enjoy running" give incorrect negations.
`nlp.statement("I enjoy running").negate().text();`
Yields:
`"I not enjoy running"`

### PR DESCRIPTION
**Pull request by ilyankou**
#145 fix

### CODE REVIEW

**Comment by spencermountain** [comment]
hey thanks!
i'm gonna start merging these guys tonight, when the heat finally dies down ;)
looks great.

**Comment by ilyankou** [comment]
Fix #152

**Comment by spencermountain** [comment]
YESSS

**Comment by spencermountain** [comment]
hey Ilya, you're the best. Wanna join the [slack group?](http://superscript-slackin.herokuapp.com)
I'm hoping that's the best place to be for collaborating on the chunky stuff going forward.
thanks!

**Pull request merged**
